### ISSUE TITLE
Issue with isONform

### ISSUE THREAD

**Issue by molbioinformatics** [aljpetri/isONform#12]
Hi, I am trying to run isONform (version 0.2.0). I manually ran pychopper, isONclust and then isONcorrect (`run_isoncorrect --t 12  --fastq_folder isONclust/fastq_files/  --outfolder isONcorrect/correction/ `). I can see that isONcorrect created "corrected_reads.fastq" fastq files in numbered subfolders in the isONcorrect/correction/ folder. Then I ran isoONform using: 
`isONform_parallel.py --fastq_folder ./isONcorrect/correction/  --outfolder ./isONform/ --split_wrt_batches --t 40`. However it spits out an error: 
**Running isONform batch_id:157828.0... creating ./isONform/168235
Running isONform batch_id:168235.0... creating ./isONform/268243
Running isONform batch_id:268243.0... creating ./isONform/146478
Running isONform batch_id:146478.0... multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/miniconda3/bin/isONform_parallel.py", line 51, in isONform
    subprocess.check_call(
  File "/home/user/miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/home/user/miniconda3/bin/main.py', '--fastq', '/tmp/tmpcivcbzwz/split_in_batches/157828_0.fastq', '--outfolder', './isONform/157828', '--exact_instance_limit', '50', '--k', '20', '--w', '31', '--xmin', '18', '--xmax', '80', '--delta_len', '5', '--exact', '--parallel', 'True', '--delta_iso_len_3', '30', '--delta_iso_len_5', '50']' returned non-zero exit status 2.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/miniconda3/bin/isONform_parallel.py", line 354, in <module>
    main(args)
  File "/home/user/miniconda3/bin/isONform_parallel.py", line 283, in main
    for x in pool.imap_unordered(isONform, instances):
  File "/home/user/miniconda3/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
subprocess.CalledProcessError: Command '['python', '/home/user/miniconda3/bin/main.py', '--fastq', '/tmp/tmpcivcbzwz/split_in_batches/157828_0.fastq', '--outfolder', './isONform/157828', '--exact_instance_limit', '50', '--k', '20', '--w', '31', '--xmin', '18', '--xmax', '80', '--delta_len', '5', '--exact', '--parallel', 'True', '--delta_iso_len_3', '30', '--delta_iso_len_5', '50']' returned non-zero exit status 2.**
Please let me know how can I fix this. Thanks.

**Comment by aljpetri** [comment]
Hello,
thank you for reporting the error. I have added a new release for isONform (v0.3.0) that hopefully fixes the problem.  
If the error persists, I, however, would require additional information from you to find the source.
Could you then please send me the contents of the stdout and stderr files for the instance located in ./isONform/157828?
Best,
Alex

**Comment by aljpetri** [comment]
Hi,
does the error still persist or did the new release fix the problem?
Best regards,
Alex

**Comment by alexyfyf** [comment]
I'm having the same issue with v 0.3.1
I have looked at the stderr in the corresponding isonform folder, and the message is this:
```
python: can't open file '/vast/projects/lab_davidson/yan.a/conda_env/isoncorrect/bin/main.py': [Errno 2] No such file or directory
```
I installed the isonclust, isoncorrect, isonform with pip in a conda environment (python 3.10.8).

**Comment by aljpetri** [comment]
Hi thank you very much for reporting the error. I realized that the main.py was missing in the release uploaded to pypi.
I have yanked the broken release now and uploaded a new release version '0.3.2,', for which the main.py is properly contained in the release.

**Comment by alexyfyf** [comment]
@aljpetri thank you for your update. I have updated to 0.3.2, but I got a different error this time, seems related to pool.py
```
Environment set: <multiprocessing.context.SpawnContext object at 0x2b4bee6544f0>
Using 48 cores.
Running isONform batch_id:10000.0... Running isONform batch_id:0.0... Running isONform batch_id:10001.0... Running isONform batch_id:10002.0... Running isONform batch_id:10003.0... Running isONform batch_id:10004.0... Running isONform batch_id:10005.0... Running isONform batch_id:10006.0... Running isONform batch_id:10007.0... Running isONform batch_id:10008.0... Running isONform batch_id:10009.0... Running isONform batch_id:1000.0... Running isONform batch_id:10010.0... Running isONform batch_id:10011.0... Running isONform batch_id:10012.0... Running isONform batch_id:10013.0... Running isONform batch_id:10016.0... Running isONform batch_id:10017.0... Running isONform batch_id:1001.0... Running isONform batch_id:10019.0... Running isONform batch_id:10018.0... Running isONform batch_id:10020.0... Running isONform batch_id:10014.0... Running isONform batch_id:10015.0... Running isONform batch_id:10021.0... Running isONform batch_id:10023.0... Running isONform batch_id:10022.0... Running isONform batch_id:10024.0... Running isONform batch_id:10027.0... Running isONform batch_id:10025.0... Running isONform batch_id:10026.0... Running isONform batch_id:10028.0... Running isONform batch_id:1002.0... Running isONform batch_id:10029.0... Running isONform batch_id:10033.0... Running isONform batch_id:10030.0... Running isONform batch_id:10035.0... Running isONform batch_id:10031.0... Running isONform batch_id:10036.0... Running isONform batch_id:10034.0... Running isONform batch_id:10032.0... Running isONform batch_id:10039.0... Running isONform batch_id:10037.0... Running isONform batch_id:10038.0... Running isONform batch_id:1003.0... Running isONform batch_id:10041.0... Running isONform batch_id:10042.0... Running isONform batch_id:10040.0... multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/stornext/Bioinf/data/lab_davidson/yan.a/conda_env/isoncorrect/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/stornext/Bioinf/data/lab_davidson/yan.a/conda_env/isoncorrect/bin/isONform_parallel.py", line 51, in isONform
    subprocess.check_call(
  File "/stornext/Bioinf/data/lab_davidson/yan.a/conda_env/isoncorrect/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '/vast/projects/lab_davidson/yan.a/conda_env/isoncorrect/bin/main.py', '--fastq', '/vast/scratch/users/yan.a/tmp/tmp8t_wrrn7/split_in_batches/10041_0.fastq', '--outfolder', 'A549_MCF7_directRNA/isoforms/10041', '--exact_instance_limit', '50', '--k', '20', '--w', '31', '--xmin', '14', '--xmax', '80', '--delta_len', '10', '--exact', '--parallel', 'True', '--delta_iso_len_3', '30', '--delta_iso_len_5', '50']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/stornext/Bioinf/data/lab_davidson/yan.a/conda_env/isoncorrect/bin/isONform_parallel.py", line 357, in <module>
    main(args)
  File "/stornext/Bioinf/data/lab_davidson/yan.a/conda_env/isoncorrect/bin/isONform_parallel.py", line 283, in main
    for x in pool.imap_unordered(isONform, instances):
  File "/stornext/Bioinf/data/lab_davidson/yan.a/conda_env/isoncorrect/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
subprocess.CalledProcessError: Command '['python', '/vast/projects/lab_davidson/yan.a/conda_env/isoncorrect/bin/main.py', '--fastq', '/vast/scratch/users/yan.a/tmp/tmp8t_wrrn7/split_in_batches/10041_0.fastq', '--outfolder', 'A549_MCF7_directRNA/isoforms/10041', '--exact_instance_limit', '50', '--k', '20', '--w', '31', '--xmin', '14', '--xmax', '80', '--delta_len', '10', '--exact', '--parallel', 'True', '--delta_iso_len_3', '30', '--delta_iso_len_5', '50']' returned non-zero exit status 1.
Running isONform batch_id:10043.0... Command exited with non-zero status 1
```

**Comment by alexyfyf** [comment]
> Hi thank you very much for reporting the error. I realized that the main.py was missing in the release uploaded to pypi. I have yanked the broken release now and uploaded a new release version '0.3.2,', for which the main.py is properly contained in the release.

Hi @aljpetri the new version works well. Just one small thing I noticed, the isonform did not work with relative path, not sure if this is something you could improve, but I just provided it with an absolute path, and worked it out.

Thank you.
Alex

**Comment by ksahlin** [comment]
Please take a look at the new version (v0.4.0), now in Rust and easier to install (and ~50x faster on PacBio, 10x on ONT, and more memory-frugal). and should now also handle relative paths.

Let us know if you run into problems with the new version. Closing this in the meantime.
